"""Database connection seam for chusennote.

A single place that opens database connections, so the persistence layer is
decoupled from a specific driver. SQLite stays the zero-config default and is
returned untouched. A Postgres URL routes through a thin translating wrapper:
the CRUD/read-model code is written portably (positional rows, INSERT-then-
SELECT for ids, ON CONFLICT ... DO UPDATE), so only a few SQLite-isms need
rewriting on the way to Postgres. Depends only on the leaf models module.
"""

from __future__ import annotations

import os
import re
import sqlite3

from .models import DEFAULT_DB_PATH

# A full database URL (e.g. postgres://user:pass@host/db) overrides the default
# SQLite path. Unset keeps the zero-config local SQLite behaviour.
DATABASE_URL_ENV = "CHUSENNOTE_DATABASE_URL"


def resolve_target(target: str | None = None) -> str:
    """Resolve the database target: explicit arg, else env URL, else the default
    SQLite path. Callers pass a concrete path today, so the env is only consulted
    when no target is given."""
    return target or os.environ.get(DATABASE_URL_ENV) or DEFAULT_DB_PATH


def is_postgres_url(target: str) -> bool:
    return target.startswith(("postgres://", "postgresql://"))


def dialect_of(target: str) -> str:
    return "postgres" if is_postgres_url(target) else "sqlite"


def split_statements(script: str) -> list[str]:
    """Split a DDL script into individual statements.

    ``--`` line comments are stripped first so a ``;`` inside a comment never
    splits a statement; the remaining schema is plain ``CREATE TABLE`` blocks
    separated by ``;`` with no semicolons in literals.
    """
    without_comments = re.sub(r"--[^\n]*", "", script)
    return [statement.strip() for statement in without_comments.split(";") if statement.strip()]


def adapt_sql(sql: str, dialect: str) -> str:
    """Rewrite a SQLite statement for ``dialect``.

    SQLite is returned unchanged. For Postgres: ``?`` placeholders become
    ``%s``; ``INSERT OR IGNORE`` becomes ``INSERT ... ON CONFLICT DO NOTHING``;
    and an autoincrement ``INTEGER PRIMARY KEY`` becomes an identity column.
    """
    if dialect != "postgres":
        return sql
    insert_or_ignore = re.search(r"\bINSERT\s+OR\s+IGNORE\b", sql, flags=re.IGNORECASE)
    if insert_or_ignore:
        sql = re.sub(r"\bINSERT\s+OR\s+IGNORE\b", "INSERT", sql, flags=re.IGNORECASE)
        sql = sql.rstrip().rstrip(";")
        sql = f"{sql} ON CONFLICT DO NOTHING"
    sql = re.sub(
        r"\bINTEGER\s+PRIMARY\s+KEY\b",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
        flags=re.IGNORECASE,
    )
    # psycopg's %s paramstyle treats % specially, so a literal % (e.g. in
    # LIKE 'keyword:%') must be doubled — before ? becomes %s, never after.
    sql = sql.replace("%", "%%")
    sql = sql.replace("?", "%s")
    return sql


class _PostgresConnection:
    """Thin proxy over a psycopg connection that speaks the SQLite-shaped API the
    persistence layer uses: ``execute`` / ``executescript`` plus ``with`` for a
    transaction. Each ``with connect(): ...`` block is one unit of work, so the
    connection is committed and closed on exit."""

    def __init__(self, connection) -> None:
        self._connection = connection

    def execute(self, sql: str, params: tuple = ()):  # noqa: ANN001
        return self._connection.execute(adapt_sql(sql, "postgres"), params)

    def executescript(self, script: str) -> "_PostgresConnection":
        for statement in split_statements(script):
            self._connection.execute(adapt_sql(statement, "postgres"))
        return self

    def commit(self) -> None:
        self._connection.commit()

    def rollback(self) -> None:
        self._connection.rollback()

    def close(self) -> None:
        self._connection.close()

    def __enter__(self) -> "_PostgresConnection":
        self._connection.__enter__()
        return self

    def __exit__(self, *exc_info: object) -> object:
        try:
            return self._connection.__exit__(*exc_info)
        finally:
            self._connection.close()


def connection_dialect(connection: object) -> str:
    """The dialect of an open connection, so schema code can branch on the few
    SQLite-only operations (PRAGMA, table introspection)."""
    return "postgres" if isinstance(connection, _PostgresConnection) else "sqlite"


def connect(target: str | None = None):
    """Open a database connection for ``target``.

    ``target`` is a SQLite file path (returned as a raw sqlite3 connection,
    unchanged) or a Postgres URL (returned as a translating wrapper). Postgres
    needs the optional ``psycopg`` driver, surfaced as a clear error if missing.
    """
    resolved = resolve_target(target)
    if not is_postgres_url(resolved):
        return sqlite3.connect(resolved)
    try:
        import psycopg
    except ImportError as error:
        raise OSError(
            "Postgres backend requires psycopg (pip install 'psycopg[binary]')"
        ) from error
    return _PostgresConnection(psycopg.connect(resolved, autocommit=False))
